name: Deploy

on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:

jobs:
  build_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install packages
        run: npm install
      - name: Build
        run: npm run build
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.2
        with:
          ftp-server: ftp://azech.tech
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./public_html/
    
